{{- range tuple "a" "b" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm_chart.fullname" $ }}-worker-{{ . }}
  labels:
    {{- include "helm_chart.labels" $ | nindent 4 }}-worker-{{ . }}
spec:
  replicas: {{ $.Values.workerReplicaCount }}
  selector:
    matchLabels:
      {{- include "helm_chart.selectorLabels" $ | nindent 6 }}-worker-{{ . }} 
  strategy:
    type: {{ $.Values.deploymentStrategy.type }}
    {{- if eq $.Values.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ $.Values.deploymentStrategy.maxSurge }}
      maxUnavailable: {{ $.Values.deploymentStrategy.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "helm_chart.selectorLabels" $ | nindent 8 }}-worker-{{ . }} 
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "helm_chart.selectorLabels" $ | nindent 20 }}-worker-{{ . }} 
                topologyKey: kubernetes.io/hostname
              weight: 1
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets }}
      containers:
        - name: mmseqs-web-worker
          image: "{{ $.Values.image.web_worker.repository }}:{{ $.Values.image.web_worker.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.web_worker.pullPolicy }}
          command: [ "/sbin/tini" ]
          args: [ "-s", "--", "/usr/local/bin/mmseqs-web", "-worker", "-config", "/etc/mmseqs-web/config.json" ]
          volumeMounts:
            - mountPath: /opt/mmseqs-web/databases
              name: {{ include "helm_chart.pvname" $ }}-{{ . }}
            - mountPath: /opt/mmseqs-web/jobs
              name: {{ include "helm_chart.pvname" $ }}-{{ . }}-jobs
            - name: {{ include "helm_chart.configmapName" $ }}
              mountPath: /etc/mmseqs-web/config.json
              subPath: config-{{ . }}.json
              readOnly: true
          resources:
            {{- toYaml $.Values.resources.worker | nindent 12 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
      volumes:
        - name: {{ include "helm_chart.pvname" $ }}-{{ . }}
          persistentVolumeClaim:
            claimName: {{ include "helm_chart.pvname" $ }}-{{ . }}
        - name: {{ include "helm_chart.pvname" $ }}-{{ . }}-jobs
          persistentVolumeClaim:
            claimName: {{ include "helm_chart.pvname" $ }}-{{ . }}-jobs
        - name: {{ include "helm_chart.pvname" $ }}-{{ . }}-workflow
          persistentVolumeClaim:
            claimName: {{ include "helm_chart.pvname" $ }}-{{ . }}-workflow
        - name: {{ include "helm_chart.configmapName" $ }}
          configMap:
            name: {{ include "helm_chart.configmapName" $ }}
            defaultMode: 0744
        - name: {{ include "helm_chart.dbParamsName" $ }}
          configMap:
            name: {{ include "helm_chart.dbParamsName" $ }}
{{- end }}