# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

imagePullSecrets: "harbor-docker-registry-conf"

# The Docker image reference which this Helm chart will run.
image:
  redis:
    repository: "harbor.devops.k8s.rcsb.org/dockerhub/library/redis"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "alpine"
  web_api:
    repository: "harbor.devops.k8s.rcsb.org/dockerhub/soedinglab/mmseqs2-app-backend"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    #tag: ""
  web_worker:
    repository: "harbor.devops.k8s.rcsb.org/dockerhub/soedinglab/mmseqs2-app-backend"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    #tag: ""
  web_webserver:
    repository: "harbor.devops.k8s.rcsb.org/dockerhub/soedinglab/mmseqs2-app-frontend"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    #tag: ""

ephemeralVolumes:
  redis_volume:
    sizeLimit: 500Mi
  databases:
    sizeLimit: 60Gi
  jobs:
    sizeLimit: 100Mi

deploymentStrategy:
  #https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  #Type is either RollingUpdate or Recreate
  type: "RollingUpdate"
  #For rolling update, what percentage of total pods can be created above desired amount
  maxSurge: 25%
  #For rolling update, what percentage of total pods can be brought down to update
  maxUnavailable: 25%

# securityContext sets the container security values of the Pod. These default values are the recommended
# values for all applications. Adjust as needed for your application purposes, but be aware of the security
# implications from these changes.
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# service declares the type of Service resource to be created, as well as the target port of the Pod to send requests.
service:
  type: ClusterIP
  port: 80

# ingress declares the Ingress resource to be created and allow access to the service from the external internet.
# Set ingress.enabled to true to create this Ingress resource. Double-check the host values for your application.
ingress:
  enabled: true
  className: "haproxy"
  annotations:
    cert-manager.io/cluster-issuer: rutgers-acme
    kubernetes.io/tls-acme: "true"
  host: seqsearch.west.k8s.rcsb.org
  path: /
  pathType: ImplementationSpecific

# Define resource limits for your application. Especially important if you enable autoscaling for this Helm chart.
# Deploy without limits first to test the application performance, then tune afterwards to ensure that autoscaling
# will work as expected.
resources:
  redis:
    requests:
      ephemeral-storage: "10Gi"
      cpu: 10m
      memory: 64Mi
    limits:
      ephemeral-storage: "50Gi"
      cpu: 1
      memory: 1Gi
  api:
    requests:
      ephemeral-storage: "10Gi"
      cpu: 10m
      memory: 64Mi
    limits:
      ephemeral-storage: "50Gi"
      cpu: 1
      memory: 1Gi
  worker:
    requests:
      ephemeral-storage: "10Gi"
      cpu: 10m
      memory: 45Gi
    limits:
      ephemeral-storage: "50Gi"
      cpu: 1
      memory: 90Gi
  webserver:
    requests:
      ephemeral-storage: "10Gi"
      cpu: 10m
      memory: 64Mi
    limits:
      ephemeral-storage: "50Gi"
      cpu: 1
      memory: 1Gi

# Buildlocker Configurations
buildlockerRegion: "west"

# appConfigs defines ConfigMap resources which are mounted into the container environment as a file.
appConfigs:
  config.json:
    value: |-
      {
        "verbose": true,
        "server" : {
          "address"    : "localhost:3000",
          "dbmanagment": false,
          "cors"       : true
        },
        "paths" : {
          "databases"    : "/opt/mmseqs-web/databases",
          "results"      : "/opt/mmseqs-web/jobs",
          "temporary"    : "/tmp",
          "mmseqs"       : "/usr/local/bin/mmseqs"
        },
        "redis" : {
          "network"  : "tcp",
          "address"  : "localhost:6379",
          "password" : "",
          "index"    : 0
        },
        "mail" : {
          "type"      : "null",
          "sender"    : "mail@example.org",
          "templates" : {
            "success" : {
              "subject" : "Done -- %s",
              "body"    : "Dear User,\nThe results of your submitted job are available now at https://search.mmseqs.com/queue/%s .\n"
            },
            "timeout" : {
              "subject" : "Timeout -- %s",
              "body"    : "Dear User,\nYour submitted job timed out. More details are available at https://search.mmseqs.com/queue/%s .\nPlease adjust the job and submit it again.\n"
            },
            "error"   : {
              "subject" : "Error -- %s",
              "body"    : "Dear User,\nYour submitted job failed. More details are available at https://search.mmseqs.com/queue/%s .\nPlease submit your job later again.\n"
            }
          }
        }
      }
  nginx.conf:
    value: |-
      server {
        listen 80 default;
      
        client_max_body_size 100M;
      
        access_log /dev/stdout;
        error_log /dev/stdout info;
      
        root /var/www/mmseqs-web;
        index index.html;
      
        location /api {
          rewrite ^/api(/.*) $1 break;
          proxy_pass        http://localhost:3000/;
      
          proxy_set_header  Host             $host;
          proxy_set_header  X-Real-IP        $remote_addr;
          proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
        }
      
        location / {
          try_files $uri $uri/ /index.html;
        }
      
        location ~* \.(js|map|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|eot|ttf)$ {
          expires max;
          add_header Cache-Control public;
          log_not_found off;
        }
      
        location = /favicon.ico {
          log_not_found off;
          access_log off;
        }
      
        location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
        }
      }
  test.fasta:
    value: |+
      >4HHB_1
      VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR
    warm_up_query.sh:
      value: |+
        #!/bin/sh
        # Warm up seqsearch service with one query. For some reason the first query is always very slow (which makes arches time out on it). This guarantees that users don't see that problem.
        echo "# Will now warm up the server with 1 query. This will take 25 minutes"
        sleep 1440  # give time for server to init indices
        wget --post-data "q=@/tmp/test.fasta&mode=accept&database[]=pdb_and_models_protein_sequence" http://localhost/api/ticket
        sleep 60  # give time for query to execute. There's no need to look at results, just let it execute
        echo "# Done warming up"
        sleep 86400 # Sleep for 1 day before stopping and having container restart
databaseParams:
  pdb_protein_sequence.params:
    value: |-
      {
        "display": {
          "name": "PDB protein sequence (seqres)",
          "version": "$today",
          "default": true,
          "order": 0,
          "index": "-s 7.5",
          "search": "-s 7.5 --max-seqs 2000"
        }
      }
  pdb_dna_sequence.params:
    value: |-
      {
        "display": {
          "name": "PDB DNA sequence (seqres)",
          "version": "$today",
          "default": false,
          "order": 1,
          "index": "--search-type 3",
          "search": "--max-seqs 2000 --search-type 3 --strand 1"
        }
      }
  pdb_rna_sequence.params:
    value: |-
      {
        "display": {
          "name": "PDB RNA sequence (seqres)",
          "version": "$today",
          "default": false,
          "order": 2,
          "index": "--search-type 3",
          "search": "--max-seqs 2000 --search-type 3 --strand 1"
        }
      }
  models_protein_sequence.params:
    value: |-
      {
        "display": {
          "name": "Models protein sequence (seqres)",
          "version": "$today",
          "default": false,
          "order": 3,
          "index": "-s 7.5",
          "search": "-s 7.5 --max-seqs 2000"
        }
      }
  models_dna_sequence.params:
    value: |-
      {
        "display": {
          "name": "Models DNA sequence (seqres)",
          "version": "$today",
          "default": false,
          "order": 4,
          "index": "--search-type 3",
          "search": "--max-seqs 2000 --search-type 3 --strand 1"
        }
      }
  models_rna_sequence.params:
    value: |-
      {
        "display": {
          "name": "Models RNA sequence (seqres)",
          "version": "$today",
          "default": false,
          "order": 5,
          "index": "--search-type 3",
          "search": "--max-seqs 2000 --search-type 3 --strand 1"
        }
      }
  pdb_and_models_protein_sequence.params:
    value: |-
      {
        "display": {
          "name": "PDB & Models protein sequence (seqres)",
          "version": "$today",
          "default": false,
          "order": 6,
          "index": "-s 7.5",
          "search": "-s 7.5 --max-seqs 2000"
        }
      }
  pdb_and_models_dna_sequence.params:
    value: |-
      {
        "display": {
          "name": "PDB & Models DNA sequence (seqres)",
          "version": "$today",
          "default": false,
          "order": 7,
          "index": "--search-type 3",
          "search": "--max-seqs 2000 --search-type 3 --strand 1"
        }
      }
  pdb_and_models_rna_sequence.params:
    value: |-
      {
        "display": {
          "name": "PDB & Models RNA sequence (seqres)",
          "version": "$today",
          "default": false,
          "order": 8,
          "index": "--search-type 3",
          "search": "--max-seqs 2000 --search-type 3 --strand 1"
        }
      }