name: Seqsearch Rolling Restart

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  restart-k8s-seqsearch-deployment:
    name: "Restart seqsearch production deployments"
    uses: rcsb/devops-cicd-github-actions/.github/workflows/restart_k8s_deployment.yaml@master
    strategy:
      matrix:
        coast: [ 'west', 'east' ]
        path: [ 'a', 'b' ]
    with:
      namespace: production
      region: ${{ matrix.coast }} 
      deployment_name: production-rcsb-seqsearch-${{ matrix.path }}
      timeout: '105m'
